# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Metta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Metta
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  #pod 'Firebase/AdMob'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'ObjectMapper'
  pod 'PromiseKit'
  pod 'SwiftyJSON'
  pod 'SwifterSwift', '~> 4.0'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Localize-Swift'
  pod 'CryptoSwift'
  pod 'PureLayout'
  pod 'NVActivityIndicatorView'
  pod 'SwiftMessages', '~> 6.0'
  #pod 'SDWebImage', '~> 4.0'
  pod 'SkyFloatingLabelTextField'
  pod 'TPKeyboardAvoiding'
  pod 'TTTAttributedLabel'
  pod 'ESTabBarController-swift'
  pod 'CHIPageControl'
  pod 'Hero'
  pod 'lottie-ios'
  pod 'Haptica'
  pod 'SwiftRichString'
  pod 'InitialsImageView'
  pod 'AppRating'
  pod 'DAKeychain'
  pod 'BottomPopup'
  pod 'Kingfisher'
  #pod "HTagView"
  #pod 'AAInfographics' 
  pod 'Charts'
  pod 'SwipeCellKit'
  pod 'Segmentio'
  pod 'Hero'
 # pod 'AlarmKit'
  pod 'TagListView', '~> 1.0'
  pod 'JTAppleCalendar'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'GoogleSignIn'
  pod 'Movin'
  pod 'LNPopupController'
  pod 'BottomPopup'
  pod 'Japx'
  pod 'Signals', '~> 6.0'
#  pod 'AQPlayer'

end
